version: '3.1'
services:
    web:
        container_name: gcmobileservices_api
        build:
            context: .
            dockerfile: prod.Dockerfile
        volumes:
          - .:/code
          - ./static-root:/static-root
          - ./media-root:/media-root
        command: sh -c "gunicorn project1.wsgi -b 0.0.0.0:8000 --reload"
        ports:
          - "8001:8001"
        env_file:
          - .env
        networks: 
            - docker-stack_dev-network
        image: web-image
        restart: on-failure
        ports:
            - "8000:8000"
    

networks:
  docker-stack_dev-network:
      driver: bridge
