# Generated by Django 4.0 on 2022-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='costquantity',
            name='chk',
        ),
    ]
