# Generated by Django 4.0 on 2022-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
