# Generated by Django 4.0 on 2022-01-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0002_alter_validation_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='make',
            field=models.CharField(blank=True, choices=[(0, 'Abarth'), (1, 'Alfa Romeo'), (2, 'Aston Martin'), (3, 'Audi'), (4, 'Bentley'), (6, 'Bertone'), (5, 'BMW'), (7, 'Cadillac'), (8, 'Chevrolet'), (9, 'Chrysler'), (10, 'Citroen')], max_length=25, null=True),
        ),
    ]
