# Generated by Django 4.0 on 2022-02-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0002_remove_cost_vat_remove_costquantity_chk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costquantity',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='costs',
        ),
    ]
