# Generated by Django 4.0 on 2022-01-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0003_alter_validation_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='amount_vat',
            new_name='sale_vat',
        ),
        migrations.AddField(
            model_name='validation',
            name='purchase_vat',
            field=models.BooleanField(default=False),
        ),
    ]
