# Generated by Django 4.0 on 2022-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0003_remove_costquantity_cost_remove_validation_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='make',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
