# Generated by Django 4.0 on 2022-01-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0005_alter_vat_amount_alter_vat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='calculation_type',
            field=models.IntegerField(choices=[(0, 'Rebu'), (1, 'Iva')]),
        ),
    ]
