# Generated by Django 4.0 on 2022-01-15 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0006_alter_validation_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costquantity',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='costquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='validation',
            name='sale_vat',
            field=models.BooleanField(default=False),
        ),
    ]
